// PreTeX math symbol mappings (LaTeX command → Unicode)

export const MATH_SYMBOLS: Record<string, string> = {
  // ── Greek lowercase ──
  alpha: "α",
  beta: "β",
  gamma: "γ",
  delta: "δ",
  epsilon: "ε",
  varepsilon: "ε",
  zeta: "ζ",
  eta: "η",
  theta: "θ",
  vartheta: "ϑ",
  iota: "ι",
  kappa: "κ",
  lambda: "λ",
  mu: "μ",
  nu: "ν",
  xi: "ξ",
  omicron: "ο",
  pi: "π",
  varpi: "ϖ",
  rho: "ρ",
  varrho: "ϱ",
  sigma: "σ",
  varsigma: "ς",
  tau: "τ",
  upsilon: "υ",
  phi: "ϕ",
  varphi: "φ",
  chi: "χ",
  psi: "ψ",
  omega: "ω",

  // ── Greek uppercase ──
  Gamma: "Γ",
  Delta: "Δ",
  Theta: "Θ",
  Lambda: "Λ",
  Xi: "Ξ",
  Pi: "Π",
  Sigma: "Σ",
  Upsilon: "Υ",
  Phi: "Φ",
  Psi: "Ψ",
  Omega: "Ω",

  // ── Binary operators ──
  pm: "±",
  mp: "∓",
  times: "×",
  div: "÷",
  cdot: "⋅",
  ast: "∗",
  star: "⋆",
  circ: "∘",
  bullet: "∙",
  oplus: "⊕",
  ominus: "⊖",
  otimes: "⊗",
  oslash: "⊘",
  odot: "⊙",
  cap: "∩",
  cup: "∪",
  sqcap: "⊓",
  sqcup: "⊔",
  vee: "∨",
  wedge: "∧",
  setminus: "∖",
  wr: "≀",
  diamond: "⋄",
  bigcirc: "◯",
  dagger: "†",
  ddagger: "‡",
  amalg: "⨿",

  // ── Relations ──
  leq: "≤",
  le: "≤",
  geq: "≥",
  ge: "≥",
  neq: "≠",
  ne: "≠",
  sim: "∼",
  simeq: "≃",
  approx: "≈",
  cong: "≅",
  equiv: "≡",
  prec: "≺",
  succ: "≻",
  preceq: "≼",
  succeq: "≽",
  subset: "⊂",
  supset: "⊃",
  subseteq: "⊆",
  supseteq: "⊇",
  sqsubseteq: "⊑",
  sqsupseteq: "⊒",
  in: "∈",
  ni: "∋",
  notin: "∉",
  vdash: "⊢",
  dashv: "⊣",
  models: "⊨",
  perp: "⊥",
  mid: "∣",
  parallel: "∥",
  propto: "∝",
  ll: "≪",
  gg: "≫",
  nless: "≮",
  ngtr: "≯",
  nleq: "≰",
  ngeq: "≱",
  nsubseteq: "⊈",
  nsupseteq: "⊉",
  subsetneq: "⊊",
  supsetneq: "⊋",
  nprec: "⊀",
  nsucc: "⊁",
  nsim: "≁",
  ncong: "≆",
  nparallel: "∦",
  nmid: "∤",
  nvdash: "⊬",
  nVdash: "⊮",
  ntriangleleft: "⋪",
  ntriangleright: "⋫",
  ntrianglelefteq: "⋬",
  ntrianglerighteq: "⋭",
  triangleleft: "◁",
  triangleright: "▷",
  trianglelefteq: "⊴",
  trianglerighteq: "⊵",
  bowtie: "⋈",
  Join: "⋈",
  smile: "⌣",
  frown: "⌢",
  asymp: "≍",
  doteq: "≐",
  Subset: "⋐",
  Supset: "⋑",
  between: "≬",
  pitchfork: "⋔",
  backsim: "∽",
  backsimeq: "⋍",
  Vdash: "⊩",
  vDash: "⊨",
  Vvdash: "⊪",
  eqcirc: "≖",
  circeq: "≗",
  lesssim: "≲",
  gtrsim: "≳",
  lessapprox: "⪅",
  gtrapprox: "⪆",
  lessgtr: "≶",
  gtrless: "≷",
  lesseqgtr: "⋚",
  gtreqless: "⋛",
  curlyeqprec: "⋞",
  curlyeqsucc: "⋟",
  precsim: "≾",
  succsim: "≿",
  precapprox: "⪷",
  succapprox: "⪸",
  Bumpeq: "≎",
  bumpeq: "≏",
  fallingdotseq: "≒",
  risingdotseq: "≓",

  // ── Arrows ──
  leftarrow: "←",
  gets: "←",
  rightarrow: "→",
  to: "→",
  uparrow: "↑",
  downarrow: "↓",
  leftrightarrow: "↔",
  Leftarrow: "⇐",
  Rightarrow: "⇒",
  Uparrow: "⇑",
  Downarrow: "⇓",
  Leftrightarrow: "⇔",
  mapsto: "↦",
  hookrightarrow: "↪",
  hookleftarrow: "↩",
  nearrow: "↗",
  searrow: "↘",
  swarrow: "↙",
  nwarrow: "↖",
  longrightarrow: "⟶",
  longleftarrow: "⟵",
  longleftrightarrow: "⟷",
  longmapsto: "⟼",
  Longrightarrow: "⟹",
  Longleftarrow: "⟸",
  Longleftrightarrow: "⟺",
  iff: "⟺",
  rightharpoonup: "⇀",
  rightharpoondown: "⇁",
  leftharpoonup: "↼",
  leftharpoondown: "↽",
  upharpoonright: "↾",
  upharpoonleft: "↿",
  downharpoonright: "⇂",
  downharpoonleft: "⇃",
  rightleftharpoons: "⇌",
  leftrightharpoons: "⇋",
  twoheadrightarrow: "↠",
  twoheadleftarrow: "↞",
  rightrightarrows: "⇉",
  leftleftarrows: "⇇",
  upuparrows: "⇈",
  downdownarrows: "⇊",
  rightleftarrows: "⇄",
  leftrightarrows: "⇆",
  Rrightarrow: "⇛",
  Lleftarrow: "⇚",
  looparrowright: "↬",
  looparrowleft: "↫",
  curvearrowright: "↷",
  curvearrowleft: "↶",
  circlearrowright: "↻",
  circlearrowleft: "↺",
  dashrightarrow: "⇢",
  dashleftarrow: "⇠",
  multimap: "⊸",
  leadsto: "⇝",
  nleftarrow: "↚",
  nrightarrow: "↛",
  nLeftarrow: "⇍",
  nRightarrow: "⇏",
  nLeftrightarrow: "⇎",
  nleftrightarrow: "↮",

  // ── Big operators ──
  sum: "∑",
  prod: "∏",
  coprod: "∐",
  int: "∫",
  iint: "∬",
  iiint: "∭",
  oint: "∮",
  bigcup: "⋃",
  bigcap: "⋂",
  bigsqcup: "⊔",
  bigvee: "⋁",
  bigwedge: "⋀",
  bigoplus: "⨁",
  bigotimes: "⨂",
  bigodot: "⨀",
  biguplus: "⨄",

  // ── Miscellaneous symbols ──
  infty: "∞",
  partial: "∂",
  nabla: "∇",
  forall: "∀",
  exists: "∃",
  nexists: "∄",
  emptyset: "∅",
  varnothing: "∅",
  neg: "¬",
  lnot: "¬",
  surd: "√",
  sqrt: "√",
  top: "⊤",
  bot: "⊥",
  angle: "∠",
  measuredangle: "∡",
  sphericalangle: "∢",
  triangle: "△",
  backslash: "∖",
  prime: "′",
  ell: "ℓ",
  wp: "℘",
  Re: "ℜ",
  Im: "ℑ",
  aleph: "ℵ",
  beth: "ℶ",
  gimel: "ℷ",
  daleth: "ℸ",
  hbar: "ℏ",
  imath: "ı",
  jmath: "ȷ",
  ldots: "…",
  dots: "…",
  cdots: "⋯",
  vdots: "⋮",
  ddots: "⋱",
  colon: ":",
  sharp: "♯",
  flat: "♭",
  natural: "♮",
  clubsuit: "♣",
  diamondsuit: "♢",
  heartsuit: "♡",
  spadesuit: "♠",
  S: "§",
  P: "¶",
  dag: "†",
  ddag: "‡",
  checkmark: "✓",
  maltese: "✠",
  complement: "∁",
  eth: "ð",
  Finv: "Ⅎ",
  Game: "⅁",
  mho: "℧",
  hslash: "ℏ",
  Bbbk: "𝕜",
  circledR: "®",
  circledS: "Ⓢ",
  diagup: "╱",
  diagdown: "╲",
  therefore: "∴",
  because: "∵",

  // ── Spacing ──
  quad: " ",
  qquad: "  ",

  // ── Text symbols ──
  textdegree: "°",
  degree: "°",
  copyright: "©",
  registered: "®",
  trademark: "™",
  pounds: "£",
  yen: "¥",
  euro: "€",

  // ── Delimiters ──
  langle: "⟨",
  rangle: "⟩",
  lceil: "⌈",
  rceil: "⌉",
  lfloor: "⌊",
  rfloor: "⌋",
  lbrace: "{",
  rbrace: "}",
  lbrack: "[",
  rbrack: "]",
  lvert: "|",
  rvert: "|",
  lVert: "‖",
  rVert: "‖",
  ulcorner: "⌜",
  urcorner: "⌝",
  llcorner: "⌞",
  lrcorner: "⌟",
  lgroup: "⟮",
  rgroup: "⟯",
  lmoustache: "⎰",
  rmoustache: "⎱",

  // ── Negated arrows/relations (additional) ──
  land: "∧",
  lor: "∨",

  // ── Misc math ──
  star2: "⋆",
  square: "□",
  blacksquare: "■",
  lozenge: "◊",
  blacklozenge: "⧫",
  blacktriangle: "▲",
  blacktriangledown: "▼",
  bigstar: "★",
  circledast: "⊛",
  circledcirc: "⊚",
  circleddash: "⊝",
  boxplus: "⊞",
  boxminus: "⊟",
  boxtimes: "⊠",
  boxdot: "⊡",
  divideontimes: "⋇",
  ltimes: "⋉",
  rtimes: "⋊",
  leftthreetimes: "⋋",
  rightthreetimes: "⋌",
  curlyvee: "⋎",
  curlywedge: "⋏",
  veebar: "⊻",
  barwedge: "⊼",
  doublebarwedge: "⩞",
  intercal: "⊺",
  smallsetminus: "∖",
  dotplus: "∔",
  centerdot: "⋅",
  Cap: "⋒",
  Cup: "⋓",

  // ── Letterlike ──
  AA: "𝔸",
  BB: "𝔹",
  CC: "ℂ",
  DD: "𝔻",
  EE: "𝔼",
  FF: "𝔽",
  GG: "𝔾",
  HH: "ℍ",
  II: "𝕀",
  JJ: "𝕁",
  KK: "𝕂",
  LL: "𝕃",
  MM: "𝕄",
  NN: "ℕ",
  OO: "𝕆",
  PP: "ℙ",
  QQ: "ℚ",
  RR: "ℝ",
  SS: "𝕊",
  TT: "𝕋",
  UU: "𝕌",
  VV: "𝕍",
  WW: "𝕎",
  XX: "𝕏",
  YY: "𝕐",
  ZZ: "ℤ",
}

// Accent commands map to combining Unicode characters
export const ACCENT_SYMBOLS: Record<string, string> = {
  hat: "\u0302",      // combining circumflex
  check: "\u030C",    // combining caron
  tilde: "\u0303",    // combining tilde
  bar: "\u0304",      // combining macron
  overline: "\u0305", // combining overline
  dot: "\u0307",      // combining dot above
  ddot: "\u0308",     // combining diaeresis
  dddot: "\u20DB",    // combining three dots above
  vec: "\u20D7",      // combining right arrow above
  acute: "\u0301",    // combining acute
  grave: "\u0300",    // combining grave
  breve: "\u0306",    // combining breve
  ring: "\u030A",     // combining ring above
  mathring: "\u030A", // combining ring above
  widehat: "\u0302",  // combining circumflex (wide variant handled by renderer)
  widetilde: "\u0303",// combining tilde (wide variant handled by renderer)
  underline: "\u0332",// combining low line
  underdot: "\u0323", // combining dot below
}

// Big operators — parser uses this to identify operators that take limits
export const BIG_OPERATORS = new Set<string>([
  "sum",
  "prod",
  "coprod",
  "int",
  "iint",
  "iiint",
  "oint",
  "bigcup",
  "bigcap",
  "bigsqcup",
  "bigvee",
  "bigwedge",
  "bigoplus",
  "bigotimes",
  "bigodot",
  "biguplus",
  "lim",
  "limsup",
  "liminf",
  "sup",
  "inf",
  "min",
  "max",
  "det",
  "Pr",
  "gcd",
  "deg",
  "hom",
  "ker",
  "dim",
  "arg",
  "injlim",
  "projlim",
  "varlimsup",
  "varliminf",
  "varinjlim",
  "varprojlim",
])

// Delimiter commands recognized by \left, \right, \big, etc.
export const DELIMITER_COMMANDS = new Set<string>([
  "langle",
  "rangle",
  "lceil",
  "rceil",
  "lfloor",
  "rfloor",
  "lbrace",
  "rbrace",
  "lbrack",
  "rbrack",
  "lvert",
  "rvert",
  "lVert",
  "rVert",
  "ulcorner",
  "urcorner",
  "llcorner",
  "lrcorner",
  "lgroup",
  "rgroup",
  "lmoustache",
  "rmoustache",
  "uparrow",
  "downarrow",
  "Uparrow",
  "Downarrow",
  "updownarrow",
  "Updownarrow",
  "backslash",
])

// Accent commands that take one argument and apply a combining character
export const ACCENT_COMMANDS = new Set<string>(Object.keys(ACCENT_SYMBOLS))
